#!/bin/bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew upgrade
brew install wget
brew install tmux
brew install git
brew install fzf
brew install nvim
brew install chruby
brew install ruby-install --HEAD
brew install golang
brew install mariadb
brew install nvm
brew install yarn

brew cask install alacritty

brew tap homebrew/cask-fonts
brew cask install font-blexmono-nerd-font
